name: 📏 New Scale Request (Cylindric)
description: Request a new default scale for a cylindric container.
title: "[Scale]: "
labels: ["automatic-scale-request"]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Is new
      description: I confirm that I searched the available scales and will only submit requests for scales that are not yet available.
      options:
        - label: The scale I request is not yet available.
          required: true
  - type: dropdown
    id: containerForm
    attributes:
      label: Container form
      description: Choose the form of the container the scale should be calculated for.
      multiple: false
      options:
        - cylinder
      default: 0
  - type: dropdown
    id: lengthUnit
    attributes:
      label: "Length Unit"
      description: The length unit that you give your measurements in.
      multiple: false
      options:
        - "mm"
        - "in"
      default: 0
  - type: dropdown
    id: volumeUnit
    attributes:
      label: Volume unit
      description: What volume unit should your scale use?
      multiple: false
      options:
        - "l"
        - "gal (U.S.)"
      default: 0
  - type: input
    id: diameter
    attributes:
      label: Inner diameter
      description: The inner diameter of your container to calculate the volme.
      placeholder: "e.g. 350"
    validations:
      required: true
  - type: input
    id: height
    attributes:
      label: Container height
      description: Height of the container to calculate the volumes of the scale.
      placeholder: "e.g. 335"
    validations:
      required: true
  - type: input
    id: minVolume
    attributes:
      label: Min. Volume
      description: The minimum volume that should appear on the scale.
      placeholder: "1"
      value: "1"
    validations:
      required: true
  - type: input
    id: maxVolume
    attributes:
      label: Max. Volume
      description: The maximum volume that should appear on the scale. Use 0 for no maximum.
      placeholder: "0"
      value: "0"
  - type: input
    id: description
    attributes:
      label: Description
      description: Describe what this scale is for and how it will look.
      placeholder: "Scale for 350mm diameter cylindric container. 1-30 l in 1 l intervals with text every 5 l."
    validations:
      required: true
  - type: textarea
    id: graduationMarks
    attributes:
      label: Graduation mark settings
      description: Anything you want the scale to be different than the default. Keep in mind that this may take longer to get created as it will be manual work to do it.
